### ISSUE TITLE
Unify release note templates

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/thunderbird-notes#24]
@Sancus and I were talking about removing the templates from this repo, and having the preview script download the approriate templates if they're missing as an initial step before rendering. 

We'll have to carry over any edits done here for preview purposes into the template on thunderbird-website. Which I believe is just adding bug ticket numbers/links? They can still be locked behind a `is preview` flag though. 

This won't be done before the website redesign. But if anyone has any thoughts feel free to voice 'em!

**Comment by jfx2006** [comment]
I mostly unified the template a while ago to make this eventual step easier. But looking at the current diff of those copies...

There's some formatting fixes in the thunderbird-notes copy.

On the website, `is_preview` is called `is_beta`. It serves the same purpose of displaying or not displaying bug numbers. Bug numbers are displayed for only beta versions on the website. Bug numbers are included when I email notes to tb-drivers and tb-support prior to a release.

So ... let's change that a bit... call it `show_bugs`.  Does this work? *untested*...

```jinja
{% set channel_name = channel_name|default('') %}
{% set show_bugs = channel_name == "Beta" or is_preview|default(False) %}
```

**Comment by JohnVeness** [comment]
Hi, I'm just an interested end-user here, but reading this made be remember that sometimes I would like to see the bug numbers in non-beta release notes. Is it possible for there to be a small button or link to show these? I think there used to be a "Show all changes in this release" link which linked to a bugzilla search query of fixed issues, but that was overwhelming - I'd prefer just bug links for the curated list of changes.

Apologies that this is probably the wrong place to raise this - I can refile as a new issue, but should it be in this repo or in https://github.com/thunderbird/thunderbird-website? Thanks.

**Comment by wsmwk** [comment]
We did do that a LONG time ago.   For example [3.0.1 release notes](https://website-archive.mozilla.org/www.mozilla.org/thunderbird_releasenotes/en-us/thunderbird/3.0.1/releasenotes/) from Jan 20, 2010 https://mzl.la/3wKdqt4 (from the link in "Please see the complete list of changes in this version" that no longer works)

Those links stopped as of [version 5.0 June 2011](https://website-archive.mozilla.org/www.mozilla.org/thunderbird_releasenotes/en-us/thunderbird/5.0/releasenotes/)

**Comment by JohnVeness** [comment]
Ah yes, those are the links I remember seeing. I didn't realise it was that long ago!

Indeed, it was the bug citations for only those items that are listed in the release notes that I was interested in making optionally visible (hidden by default). The old bugzilla search links tended to give too many results, sometimes hundreds as I recall.

**Comment by Sancus** [comment]
We intentionally don't provide an option to display bug numbers on main releases because we don't want to direct large amounts of traffic to closed Bugzilla bugs. I suppose we could rethink that now that you can no longer comment on closed bugs without editbugs permissions. But the release notes are already pretty technical, this repository isn't terribly hard to find and contains all the bug numbers for every release.

**Comment by JohnVeness** [comment]
Thanks. Yes, I can well understand not wishing to draw typical endusers to bugzilla. I guess I'm in a very small niche of people who is sometimes interested to read more about a change, but who isn't so interested that I bother with beta releases! As you say, I can find the bug numbers in the yml files, so I'll just do that.

Thanks again, and sorry for derailing the discussion.
