### ISSUE TITLE
Slow to update the release notes page?

### ISSUE THREAD

**Issue by Perkolator** [thunderbird/thunderbird-notes#31]
This has been happening for a long time, the Update Manager in my Linux Mint installation almost always shows an update to TB many days, even week+ before the TB release notes page is updated.

I'm using [Mozillateam PPA](https://launchpad.net/~mozillateam/+archive/ubuntu/ppa) as the packet source.

For example, my Update Manager has been offering the update `115.12.0` for many days (and I think I actually saw it first being `115.11.2` which was over a week ago IIRC, but I guess that version was scrapped). That `115.12.0` version was published in the PPA on Jun 7. In this repo, I now found that a [release/115.12.0.yml](https://github.com/thunderbird/thunderbird-notes/commit/03762f50d7f38f19b7130221c71d63cf70f12a3f) file was created on Jun 5. I see that the file has a `release_date: '2024-06-11'` line, which was yesterday.

So, why are the TB release notes published only after many days when (at least) the linux builds are published/pushed through the official PPA? OR, why are the linux builds published before the "official"(?) release date?

Why is this happening? It would be great to see the release notes published just before/at the same time as the updates are pushed to end-users. This is how it usually works (only few exceptions comes to mind right now, VLC, TB). Thanks.

**Comment by Sancus** [comment]
Mozillateam PPA is not published by us, btw. So, it sometimes releases before we've actually published the release. That's why the release notes aren't present.

We've advised them not to do that in the future but unfortunately we can't control when distros do Thunderbird builds, so sometimes they will jump the gun.
