### ISSUE TITLE
Update 115.10.2-115.13.0 to ${version}esr

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/thunderbird-notes#41]
Since we swapped the release channel to esr starting with 115.10.2 iirc we should append `esr` to the end of these yml files.

ex/ 115.13.0.yml -> 115.13.0esr.yml

We recently updated live.thunderbird redirects so this is now a bit of a problem: https://github.com/thunderbird/live-redirects/commit/c8e1c1bb9db8d25ec4863af50a5e6d1a2ade8fce

Related bug: https://github.com/thunderbird/thunderbird-website/issues/627

**Comment by coreycb** [comment]
I believe this is fixed in https://github.com/thunderbird/thunderbird-notes/commit/79d4f3020ed86291c65c27951f8e10dfc5919e12

**Comment by MelissaAutumn** [comment]
Thanks!
