### ISSUE TITLE
Correction to release notes "tell us what you think"

### ISSUE THREAD

**Issue by wsmwk** [thunderbird/thunderbird-notes#43]
A user reported that "tell us what you think" sends them to Support AAQ, i.e. https://support.mozilla.org/en-US/questions/new/thunderbird.  That link should be https://connect.mozilla.org/

", ask for help" pointing to https://support.mozilla.org/en-US/questions/new/thunderbird could be a second clause.

So then we would have "As always, you’re encouraged to tell us what you think, ask for help, or file a bug in Bugzilla.

**Comment by coreycb** [comment]
It turns out this code is in the thunderbird-website source so I've opened an issue at https://github.com/thunderbird/thunderbird-website/issues/659

**Comment by Sancus** [comment]
This was fixed.
